In [1]:
import numpy as np

In [4]:
#Задание 1
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix_1 = matrix + np.eye(3)
matrix_1 @ np.array([1,2,3])

array([15., 34., 53.])

In [6]:
np.transpose(matrix_1)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [7]:
np.linalg.inv(matrix_1)

array([[-6. , -2. ,  3. ],
       [-1. ,  0.5,  0. ],
       [ 5. ,  1. , -2. ]])

In [8]:
#Задание 2
m = np.array([[2, 2],[1, 3]])
np.linalg.eig(m)

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [10]:
#Задание 3
np.linalg.det(np.array([[2,-3,-7], [9,8,-2], [2,5,4]]))

1.0000000000000022